### PR TITLE
GC prompt fixes

### LINKED ISSUE #198: GC Popup OK button is unresponsive on some devices
I was not able to reproduce, however there are few reports of this bug in the App Reviews and emailed directly from users.

### PR DESCRIPTION
**Pull request by TinasheMzondiwa**
# What did you change:

Closes #198 

- Refactored shared pref logic
- Enabled close when you touch outside
- Added a close button to the top right

# Screenshot/GIFs of this change

Screenshot_20210521-190526

# Merge checklist

- [x] Automated (unit/ui) tests
- [x] Manual tests

### CODE REVIEW

File: features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesViewModel.kt [hunk 1]
```diff
@@ -102,7 +102,7 @@ class QuarterliesViewModel @Inject constructor(
                             mutableShowLanguagePrompt.call()
                         }
                     } else {
-                        _appReBranding.emit(!ssPrefs.isAppReBrandingPromptShown())
+                        handleBandingPrompt()
```
Comment (merlin-zaraza) [inline features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesViewModel.kt]: Typo, should be `handleBrandingPrompt `

File: features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesViewModel.kt [hunk 2]
```diff
@@ -120,7 +120,10 @@ class QuarterliesViewModel @Inject constructor(
         ssPrefs.setLanguagePromptSeen()
     }
 
-    fun reBrandingPromptSeen() {
-        ssPrefs.setAppReBrandingShown()
+    private suspend fun handleBandingPrompt() {
```
Comment (merlin-zaraza) [inline features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesViewModel.kt]: typo, same as above

File: features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesActivity.kt [hunk 3]
```diff
@@ -162,17 +159,18 @@ class QuarterliesActivity : SSBaseActivity() {
 
     private fun showAppReBrandingPrompt() {
         val view = layoutInflater.inflate(R.layout.ss_prompt_app_re_branding, null)
```
Comment (merlin-zaraza) [inline features/lessons/src/main/java/com/cryart/sabbathschool/lessons/ui/quarterlies/QuarterliesActivity.kt]: I think view binding should work here, it will allow to omit `findViewById`

**Review by merlin-zaraza — APPROVED** [review]
Few comments, not critical

**Comment by VitalikL** [comment]
@TinasheMzondiwa I suggest we don't need the "OK" button now

**Comment by TinasheMzondiwa** [comment]
> @TinasheMzondiwa I suggest we don't need the "OK" button now

Ok, removing...
